version: '3.5'
services:    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: docker-compose-elasticsearch
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 5209:9200
    networks:
      - backend
  mariadb:
    image: mariadb:10.3
    container_name: docker-compose-mariadb
    restart: always
    volumes: 
      - mariadb-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=mandarinkb
    ports:
      - 3306:3306
    networks:
      - backend    
  app-api:
    depends_on:
      - mariadb
      - elasticsearch
    image: mandarinkb/project-final-api:1.1
    expose:
      - "8888"   
    networks:
      - backend 
  load-balancer:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-api
    image: nginx:1.18.0-alpine
    container_name: docker-compose-load-balancer
    ports:
      - 9999:9999
    networks:
      - backend 
  # app-ui:
  #   depends_on:
  #     - load-balancer
  #   image: mandarinkb/project-final-ui-controller:1.0
  #   container_name: docker-compose-ui-controller
  #   ports:
  #     - 4200:80
  #   networks:
  #     - backend        
networks:
  backend:       
volumes:
  elasticsearch-data:
  mariadb-data:

# parth /var/lib/docker/volumes
# comment press ctrl+/
